syntax = "proto3";

package chat;

service ChatInternal {
  rpc GetChatMembers (ChatIdRequest) returns (MembersResponse);
  rpc IsMember (MembershipRequest) returns (MembershipResponse);
  rpc SendMessageInternal (SendMessageInternalRequest) returns (SendMessageInternalResponse);
  rpc GetUnreadMessages (UnreadMessagesRequest) returns (UnreadMessagesResponse);
}

message SendMessageInternalRequest{
  string chatId = 1;
  string senderId = 2;
  string content = 3;
}

message SendMessageInternalResponse {
  bool success = 1;
  string messageId = 2;
  string error = 3;
}

message ChatIdRequest {
  string chatId = 1;
}

message MembersResponse {
  repeated string memberIds = 1;
}

message MembershipRequest {
  string chatId = 1;
  string userId = 2;
}

message MembershipResponse {
  bool isMember = 1;
}

message UnreadMessagesRequest {
  string userId = 1;
  int32 maxMessagesPerChat = 2;
}

message UnreadMessage {
  string messageId = 1;
  string senderId = 2;
  string content = 3;
  string type = 4;
  string createdAt = 5;
}

message UnreadChat {
  string chatId = 1;
  string chatType = 2;
  string title = 3;
  string otherMemberId = 4;
  repeated UnreadMessage messages = 5;
}

message UnreadMessagesResponse {
  repeated UnreadChat chats = 1;
}